### ISSUE TITLE
APIkey error on non-aws bucket

### ISSUE THREAD

**Issue by Dark-Matter7232** [mtlynch/logpaste#114]
Trying to use filebase as bucket results in this error, using it with other programs I get no such error(s3fs)
```
monitor error: cannot lookup bucket region: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```
My litestream.yml
```
access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
dbs:
  - path: ${DB_PATH}
    replicas:
      - url: s3://mypaste-new.filebase.com
        sync-interval: ${DB_SYNC_INTERVAL}
```

**Comment by mtlynch** [comment]
Thanks for reporting this! It looks like Litestream can't yet parse Filebase URLs natively (https://github.com/benbjohnson/litestream/issues/204), but you can work around this by setting the values explicitly:

```yaml
...
  replicas:
    - type: s3
      endpoint: https://s3.filebase.com
      bucket: mypaste-new
      path: .
```
